# Generated by Django 2.1.1 on 2019-01-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': '出版社'},
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.IntegerField(choices=[(1, '已出版'), (2, '未出版')], default=1),
        ),
    ]
